ERROR    root:import_views.py:69 Error importing book
Traceback (most recent call last):
  File "/home/runner/work/lexiflux/lexiflux/lexiflux/views/import_views.py", line 47, in import_book
    book = import_url(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/lexiflux/lexiflux/lexiflux/views/import_views.py", line 166, in import_url
    raise ValueError("No URL provided")
ValueError: No URL provided